package ServerClientMain;

import RMI.ClientRMI;

import java.io.IOException;
import java.rmi.NotBoundException;

public class AutoClientThread implements Runnable {
    private int threadID;
    private ClientRMI clientRMI;

    public AutoClientThread(int threadID) throws NotBoundException, IOException {
        this.threadID = threadID;
        this.clientRMI = new ClientRMI(threadID);
    }

    @Override
    public void run() {
        try {
            clientRMI.initializeGraph("input_graph.txt");
            clientRMI.runAutoGeneratedBatches(1);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
}
