package ServerClientMain;

import RMI.ClientRMI;

public class Client {

    public static void main(String[] args) {
        try {
            ClientRMI clientRMI = new ClientRMI();
            clientRMI.initializeGraph();
            clientRMI.runAutoGeneratedBatches(3);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
}

